version: "3"
services:
  app:
    build:
      context: .
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - database
    ports:
      - 8083:80
      - 446:445
    networks:
      - app-network
  database:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shop_backup
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - app-network
  phpma:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pma_backup
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - PMA_USER=root
      - PMA_PASSWORD=password
    links:
      - database:db
    depends_on:
      - database
    ports:
      - 8087:80
    networks:
      - app-network
networks:
  app-network:
    driver: bridge